name: Bug Report
description: Report a bug or issue with RapidRAW
title: "BUG: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

        > **Note:** This template is for reporting bugs and issues only. For feature requests, please use the [Discussions page](../../discussions) instead.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem you encountered including error messages (if any).
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Tell us what you thought should happen instead.
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce this?
      description: List the steps to recreate the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...

  - type: markdown
    attributes:
      value: "### Your Environment"

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - macOS Apple Silicon
        - macOS Intel
        - Ubuntu 24.04
        - Ubuntu 22.04
        - Other Linux
        - Other (please specify in additional info)
    validations:
      required: true

  - type: input
    id: rapidraw-version
    attributes:
      label: RapidRAW Version
      description: What version of RapidRAW are you using?
      placeholder: e.g., v1.4.3
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any other details that might help us understand the problem?
      placeholder: Any other context, workarounds you've tried, GPU driver version, etc...

  - type: markdown
    attributes:
      value: |
        ### Lenses & Camera Support

        RapidRAW relies on external libraries for lens corrections and raw file decoding. If your camera or lens is unsupported, please open an issue directly with the relevant project:

        | Feature | Library | Request addition |
        |---|---|---|
        | Lens corrections | [lensfun](https://github.com/lensfun/lensfun/) | [Open an issue](https://github.com/lensfun/lensfun/issues/new) |
        | Raw file decoding | [dnglab](https://github.com/dnglab/dnglab/) | [Open an issue](https://github.com/dnglab/dnglab/issues/new) |

  - type: checkboxes
    id: acknowledgement-checkboxes
    attributes:
      label: Acknowledgement
      options:
        - label: I have verified that my camera and lenses are supported by the external libraries listed above, or my issue is unrelated to camera/lens support.
          required: true
        - label: I have searched all existing issues, both open and closed, and did not find a duplicate.
          required: true
